version: "2"
services:
  biblio:
    build: .
    restart: always
    ports:
      - 8080:8080
    volumes:
      - ./data:/app/data
  grobid:
    image: lfoppiano/grobid:0.5.5
    restart: always
    ports:
      - 8070:8070
  elasticsearch:
    image: elasticsearch:6.7.1
    environment:
      - "discovery.type=single-node"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    restart: always
volumes:
  elasticsearch-data:
    driver: local
